# class inheritance template generated by chatgpt and modified by me
from message import Message
from datetime import datetime, UTC

class ImageSubmittedMessage(Message):
    _counter = 0  # class-level counter (per child)

    def __init__(self, image_id: str, path: str, source: str):
        payload = {
            "image_id": image_id,
            "path": path,
            "source": source,
            "submitted_time": datetime.utcnow().isoformat()
        }
        super().__init__(payload)

    def _get_topic(self):
        return "image_submitted"

    def _generate_event_id(self):
        ImageSubmittedMessage._counter += 1
        return f"IS_{ImageSubmittedMessage._counter}"

class InferenceCompletedMessage(Message):
    _counter = 0

    def __init__(self, image_metadata: str, annotation_metadata: str):
        payload = {
            "image_metadata": image_metadata,
            "annotation_metadata": annotation_metadata,
            "completed_time": datetime.utcnow().isoformat()
        }
        super().__init__(payload)

    def _get_topic(self):
        return "inference_completed"

    def _generate_event_id(self):
        InferenceCompletedMessage._counter += 1
        return f"IC_{InferenceCompletedMessage._counter}"