import json

# generated by chatgpt
class Message:
    def __init__(self, payload: dict):
        self.type = "publish"
        self.topic = self._get_topic()
        self.event_id = self._generate_event_id()
        self.payload = payload

    def _get_topic(self):
        raise NotImplementedError("Child class must define topic")

    def _generate_event_id(self):
        raise NotImplementedError("Child class must define event_id logic")

    def to_json(self):
        return json.dumps({
            "type": self.type,
            "topic": self.topic,
            "event_id": self.event_id,
            "payload": self.payload,
        }, indent=2)

