import json

# generated by chatgpt
class Message:
    def __init__(self, payload: dict):
        self.type = "publish"
        self.topic = self._get_topic()
        self.event_id = self._generate_event_id()
        self.payload = payload

    def _get_topic(self):
        raise NotImplementedError("Child class must define topic")

    def _generate_event_id(self):
        raise NotImplementedError("Child class must define event_id logic")

    def get_payload_value(self, key: str):
        if key not in self.payload:
            raise KeyError(f"Payload key '{key}' not found")
        return self.payload[key]

    def to_json(self):
        return json.dumps({
            "type": self.type,
            "topic": self.topic,
            "event_id": self.event_id,
            "payload": self.payload,
        }, indent=2)


# Example "image_submitted"
# {'type': 'publish',
# 'topic': 'image_submitted',
# 'event_id': 'IS_1',
#  'payload': {'image_id': 'some_id',
#              'path': 'photos\\some_id',
#              'source': 'user_upload'}}
class ImageSubmittedMessage(Message):
    _counter = 0  # class-level counter (per child)

    def __init__(self, image_id: str, path: str, source: str):
        payload = {
            "image_id": image_id,
            "path": path,
            "source": source,
        }
        super().__init__(payload)

    def _get_topic(self):
        return "image_submitted"

    def _generate_event_id(self):
        ImageSubmittedMessage._counter += 1
        return f"IS_{ImageSubmittedMessage._counter}"

class AnnotationCompletedMessage(Message):
    _counter = 0

    def __init__(self, image_metadata: str, annotation_metadata: str):
        payload = {
            "image_metadata": image_metadata,
            "annotation_metadata": annotation_metadata,
        }
        super().__init__(payload)

    def _get_topic(self):
        return "inference_completed"

    def _generate_event_id(self):
        AnnotationCompletedMessage._counter += 1
        return f"IC_{AnnotationCompletedMessage._counter}"

class AnnotationStoredMessage(Message):
    _counter = 0

    def __init__(self, image_metadata: str):
        payload = {
            "image_metadata": image_metadata,
        }
        super().__init__(payload)

    def _get_topic(self):
        return "annotation_stored"

    def _generate_event_id(self):
        AnnotationStoredMessage._counter += 1
        return f"AS_{AnnotationStoredMessage._counter}"

class EmbeddingCreatedMessage(Message):
    _counter = 0

    def __init__(self, image_metadata: str, embedding_data: str):
        payload = {
            "image_metadata": image_metadata,
            "embedding_data": embedding_data,
        }
        super().__init__(payload)

    def _get_topic(self):
        return "embedding_created"

    def _generate_event_id(self):
        EmbeddingCreatedMessage._counter += 1
        return f"EC_{EmbeddingCreatedMessage._counter}"

class EmbeddingStoredMessage(Message):
    _counter = 0

    def __init__(self, image_metadata: str, embedding_data: str):
        payload = {
            "image_metadata": image_metadata,
            "embedding_data": embedding_data,
        }
        super().__init__(payload)

    def _get_topic(self):
        return "embedding_stored"

    def _generate_event_id(self):
        EmbeddingStoredMessage._counter += 1
        return f"ES_{EmbeddingStoredMessage._counter}"

# -------------HERE ARE THE QUERY MESSAGES -----------------------
class QueryImagesSubmitted(Message):
    _counter = 0

    def __init__(self, query_images_submitted: str, k: int):
        payload = {
            "query_images_submitted": query_images_submitted,
            "k": k,
        }
        super().__init__(payload)

    def _get_topic(self):
        return "query_images_submitted"

    def _generate_event_id(self):
        QueryImagesSubmitted._counter += 1
        return f"QIS_{QueryImagesSubmitted._counter}"

class QueryTopicsSubmitted(Message):
    _counter = 0

    def __init__(self, query_topics_submitted: str, k: int):
        payload = {
            "query_topics_submitted": query_topics_submitted,
            "k": k,
        }
        super().__init__(payload)

    def _get_topic(self):
        return "query_topics_submitted"

    def _generate_event_id(self):
        QueryTopicsSubmitted._counter += 1
        return f"QIS_{QueryTopicsSubmitted._counter}"