# generated by Codex based off of AnnotDB.py

from RedisSubscriber import RedisSubscriber
from RedisPublisher import RedisPublisher
from QueueWorker import VectorDBWorker
from message import EmbeddingStoredMessage

import redis
import queue
import faiss
import numpy as np
from time import sleep
from logger import make_logger

logger = make_logger()

# Primary Vector DB processing function
def vector_db_process(message_dict, vector_db_service_pub, index, faiss_id_to_metadata):
    try:
        payload = message_dict["payload"]

        image_metadata = payload["image_metadata"]
        embedding_data = payload["embedding_data"]

        # Convert list-like embedding into Faiss-compatible vector
        embedding = np.array(embedding_data, dtype="float32")

        # Faiss expects a 2D array: shape = (number_of_vectors, embedding_dimension)
        embedding = embedding.reshape(1, -1)

        # Optional but important check
        if embedding.shape[1] != embedding_dimension:
            raise ValueError(
                f"Expected embedding dimension {embedding_dimension}, "
                f"got {embedding.shape[1]}"
            )

        # The next vector id will be current index size
        faiss_id = index.ntotal

        # Add vector to Faiss
        index.add(embedding)

        # Store metadata separately
        faiss_id_to_metadata[faiss_id] = image_metadata

        # Publish success message
        stored_msg = EmbeddingStoredMessage(image_metadata, embedding_data)
        vector_db_service_pub.publish_message("embedding_stored", stored_msg)

    except Exception:
        logger.exception("Failed to process message: %r", message_dict)


# Connect to same Redis client as other services
redis_client = redis.Redis(
    host="localhost",
    port=6379,
    decode_responses=True,
)


# Queue for Vector DB worker
vector_db_queue = queue.Queue(10)


# Subscriber: listen for completed embeddings
vector_db_service_sub = RedisSubscriber(
    "Vector Database",
    vector_db_queue,
    redis_client,
)
vector_db_service_sub.register_sub_channel("embedding_created")


# Publisher: announce stored embeddings
vector_db_service_pub = RedisPublisher(
    "Vector DB Publisher",
    redis_client,
)
vector_db_service_pub.register_pub_channel("embedding_stored")


# Set up Faiss index
# embedding_dimension should match whatever AnnotModule / embedding module produces.
embedding_dimension = 5

# Basic exact-search index to start with.
# Other options later: IndexIVFFlat, IndexHNSWFlat, IndexFlatIP.
# Create a database for <embedding_dimension>-number vectors, and search by closest Euclidean distance.
index = faiss.IndexFlatL2(embedding_dimension)


# Metadata side table
# Faiss stores vectors, but not rich metadata.
# This could start as an in-memory dict and later move to MongoDB / JSON / SQLite.
# faiss_id_to_metadata = {
#     0: {"image_id": "...", "path": "...", ...},
#     1: {"image_id": "...", "path": "...", ...},
# }
faiss_id_to_metadata = {}

# Worker
vector_db_worker = VectorDBWorker(
    vector_db_queue,
    vector_db_process,
    vector_db_service_pub,
    index,
    faiss_id_to_metadata,
)


# Start service
vector_db_worker.start()
sleep(60)
vector_db_worker.stop()
