# generated by Codex based off of AnnotDB.py

from RedisSubscriber import RedisSubscriber
from RedisPublisher import RedisPublisher
from QueueWorker import VectorDBWorker
from message import EmbeddingStoredMessage

import redis
import queue
import faiss
import numpy as np
from time import sleep
from logger import make_logger

logger = make_logger()

# Primary Vector DB processing function
def vector_db_process(message_dict, vector_db_service_pub, index, faiss_id_to_metadata):
    try:
        payload = message_dict["payload"]

        image_metadata = payload["image_metadata"]
        embedding_data = payload["embedding_data"]

        # Convert list-like embedding into Faiss-compatible vector
        embedding = np.array(embedding_data, dtype="float32")

        # Faiss expects a 2D array: shape = (number_of_vectors, embedding_dimension)
        embedding = embedding.reshape(1, -1)

        # Optional but important check
        if embedding.shape[1] != embedding_dimension:
            raise ValueError(
                f"Expected embedding dimension {embedding_dimension}, "
                f"got {embedding.shape[1]}"
            )

        # The next vector id will be current index size
        faiss_id = index.ntotal

        # Add vector to Faiss
        index.add(embedding)

        # Store metadata separately
        faiss_id_to_metadata[faiss_id] = image_metadata

        # Publish success message
        stored_msg = EmbeddingStoredMessage(image_metadata, embedding_data)
        vector_db_service_pub.publish_message("embedding_stored", stored_msg)

    except Exception:
        logger.exception("Failed to process message: %r", message_dict)


# Keep imports and vector_db_process as-is above this point.

embedding_dimension = 5


def create_vector_db_service():
    redis_client = redis.Redis(
        host="localhost",
        port=6379,
        decode_responses=True,
    )

    vector_db_queue = queue.Queue(10)

    vector_db_service_sub = RedisSubscriber(
        "Vector Database",
        vector_db_queue,
        redis_client,
    )
    vector_db_service_sub.register_sub_channel("embedding_created")

    vector_db_service_pub = RedisPublisher(
        "Vector DB Publisher",
        redis_client,
    )
    vector_db_service_pub.register_pub_channel("embedding_stored")

    index = faiss.IndexFlatL2(embedding_dimension)
    faiss_id_to_metadata = {}

    vector_db_worker = VectorDBWorker(
        vector_db_queue,
        vector_db_process,
        vector_db_service_pub,
        index,
        faiss_id_to_metadata,
    )

    return vector_db_worker


def main():
    vector_db_worker = create_vector_db_service()
    vector_db_worker.start()
    sleep(60)
    vector_db_worker.stop()


if __name__ == "__main__":
    main()
