import redis
import json
from datetime import datetime

# Generated by LLM with instructions from me
class Message:
    _counter = 0  # class-level counter (persists within runtime)

    def __init__(self, image_id: str, path: str, source: str):
        Message._counter += 1

        self.data = {
            "type": "publish",
            "topic": "image.submitted",
            "event_id": f"IS_{Message._counter}",
            "payload": {
                "image_id": image_id,
                "path": path,
                "source": source,
                "timestamp": datetime.utcnow().isoformat()
            }
        }

    def to_dict(self):
        return self.data

    def to_json(self):
        return json.dumps(self.data)

    def __repr__(self):
        return f"message(event_id={self.data['event_id']})"


# create a channel
r = redis.Redis(host='localhost', port=6379, decode_responses=True)

# name the channel
channel = "testing_message_class"

# when _____ publish event (message).
# make a message
msg1 = Message("image_id_passed", "path_passed", "source_passed")

# publish the message
#Received: {'type': 'message', 'pattern': None, 'channel': 'sensor_updates', 'data': 'temperature:20'}
r.publish(channel, msg1.to_json())

# for decoding
print(f"Published: {msg1.__repr__()}")

# some sort of STOP feature because subscribe is blocking
r.publish(channel, "STOP")

